services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - SERVER_ADDR=backend:8081  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    deploy:
      replicas: 4
    build:
      context: ./server
      dockerfile: Dockerfile
      target: builder
    stop_signal: SIGINT  
    environment:
      - SERVER_PORT=8081
    depends_on:
      - mongo

  mongo:
    image: mongo